id: P6B888641
initial_creation_type: ocr
source_metadata:
  volumes:
    b58b8898379244c98de19d26a8ed58e3:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: སྦྱིན་པའི་གཏམ།
      total_pages: 1144
      volume_number: 96
